language: cpp
compiler: gcc
#install dependencies
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install nasm clang
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
#basic build
script:
  # create a new directory
  - cd ..
  - mkdir build
  - cd build
  # run clang static analysis while building
  # see http://clang-analyzer.llvm.org/
  - scan-build cmake ../sweb
  - scan-build make
