language: cpp
compiler: gcc
#install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install nasm
#basic build
script:
  - cmake .
  # run clang static analysis while building
  # see http://clang-analyzer.llvm.org/
  - scan-build make
